server:
  port: 9090
zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    simple:
      path: /simple/**
      serviceId: simple-service
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 50000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
info:
  artifactId: "@project.artifactId@"
  description: "@project.description@"
  version: "@project.version@"
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
debug: true
trace: false
logging:
  level:
    root: DEBUG